library(dplyr)
setwd('/home/amp_prog/Downloads')
list1<-read.csv('cervical.csv')
list2<-read.csv('CRC.csv')
list3<-read.csv('ESCC.csv')
joined<-semi_join(list1, list2, by = c('x'))
results<-semi_join(joined,list3,by=c('x'))
write.csv(results,file = 'results.csv')
