https://www.bioconductor.org/packages/devel/bioc/vignettes/ChIPpeakAnno/inst/doc/pipeline.html
library(ChIPpeakAnno)
library(GenomicRanges)
library(GenomicFeatures)
setwd('/home/deviancedev/Desktop/drive_jan2024/FCCC/GSE198565_MB_G4_scATAC.hiC.scRNA')
nsc_sox11<-read.table('NSC_SOX11_IgG_summits.bed')
colnames(nsc_sox11)<-c('seqnames','start','end','peakNames','score')
nsc_sox11<-toGRanges(nsc_sox11,format='BED',header=FALSE)
View(data.frame(nsc_sox11))

mb_sox11<-read.table('MB_SOX11_IgG_summits.bed')
colnames(mb_sox11)<-c('seqnames','start','end','peakNames','score')
mb_sox11<-toGRanges(mb_sox11,format='BED',header=FALSE)
View(data.frame(mb_sox11))
break 
ol<-findOverlapsOfPeaks(nsc_sox11,mb_sox11)
ol$peaklist
makeVennDiagram(ol)
ol$all.peaks
break 
