pheatmap(tester[c('Neurod1','Cntn2','Map1a','Rbfox3',
                  'Nefl','Fyn','Reln','Unc13a',
                  'Ppp2r5b','Trim67','Cnr1','Kidins220',
                  'Dpysl3','Rims1','Atp8a2','Mapt',
                  'L1cam','Apbb1','Ss18l1',
                  'Rufy3','Ndrg4','Pacsin1','Fkbp1b',
                  'Neurod2','Sez6',
                  'Map1b'),],
         scale = 'row',
         cluster_cols = FALSE,
         cluster_rows = FALSE,
         border_color = 'grey',
         fontsize = 17,
         color = colorRampPalette(rev(brewer.pal(n=7,name='RdYlBu')))(100))
#-----------hedgehog 
pheatmap(tester[c('Ptch1','Ptch2','Smo','Gpr161','Prkaca',
                  'Prkacb','Csnk1a1','Csnk1g2','Csnk1g1',
                  'Csnk1g3','Csnk1d','Csnk1e','Gsk3b','Gli1',
                  'Gli2','Gli3','Sufu','Kif7','Hhip',
                  'Ccnd1','Ccnd2','Bcl2','Cul1','Fbxw11',
                  'Btrc','Hhat','Hhatl','Shh','Ihh','Dhh',
                  'Disp1','Scube2','Cdon','Gas1','Lrp2',
                  'Mosmo','Megf8','Mgrn1','Smurf2','Smurf1',
                  'Grk2','Grk3','Evc','Evc2','Efcab7','Iqce',
                  'Arrb1','Arrb2','Kif3a','Cul3','Spop',
                  'Spopl'),],
         scale = 'row',
         cluster_cols = FALSE,
         cluster_rows = FALSE,
         border_color = 'grey',
         fontsize = 12,
         color = colorRampPalette(rev(brewer.pal(n=7,name='RdYlBu')))(100))

